feat(git): improve pre commit hook

diff --git a/git/.git_hooks/pre-commit b/git/.git_hooks/pre-commit
--- a/git/.git_hooks/pre-commit
+++ b/git/.git_hooks/pre-commit
@@ -1,10 +1,7 @@
 #!/bin/bash
 
-LOCAL_NAME=$(git config user.name)
-LOCAL_EMAIL=$(git config user.email)
-
-GLOBAL_NAME=$(git config --global user.name)
-GLOBAL_EMAIL=$(git config --global user.email)
+USER_NAME=$(git config user.name)
+USER_EMAIL=$(git config user.email)
 
 PERMANENTLY_APPROVED=$(git rev-parse --show-toplevel)/.git/.name_and_email_approved
 
@@ -12,20 +9,33 @@ if [ -f $PERMANENTLY_APPROVED ]; then
     exit 0
 fi
 
-echo "⚠️  Please, check if user and email for the commit are correct"
-echo "  Local:   $LOCAL_NAME <$LOCAL_EMAIL>"
-echo "  Global:  $GLOBAL_NAME <$GLOBAL_EMAIL>"
+echo "Is this user correct for this repository?"
+echo "  $USER_NAME <$USER_EMAIL>"
+echo
+echo "If it is not correct, please fix it with:"
+echo "  git config user.name 'Your Name'"
+echo "  git config user.email 'Your Email'"
+echo
 
 exec < /dev/tty
 
-read -p "¿Do you want to continue? (y/n): " choice
+read -p "¿Do you want to continue with the commit? (y/n): " choice
 
 case "$choice" in
     y|Y )
         touch $PERMANENTLY_APPROVED
         echo "Nice!"
+        echo
         ;;
-    n|N ) echo "Aborted"; exit 1;;
-    * ) echo "Aborted"; exit 1;;
+    n|N ) 
+        echo "Aborted"
+        echo
+        exit 1
+        ;;
+    * ) 
+        echo "Aborted"
+        echo
+        exit 1
+        ;;
 esac
 
